---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apache
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/VMCluster/infrastructure/apps/apache
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
