---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: awx-operator
  namespace: awx
spec:
  interval: 5m0s
  path: ./config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: awx
