---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: awx
  namespace: awx 
spec:
  interval: 5m0s
  ref:
    tag: 2.19.1
  url: https://github.com/ansible/awx-operator.git
