---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./cluster/VMCluster/infrastructure/cluster/storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
