---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: awx-operator
  namespace: flux-system
spec:
  interval: 5m
  path: ./config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: awx
  targetNamespace: awx
  wait: true
